apiVersion: v1
kind: Service
metadata:
  name: plana-task1
spec:
  selector:
    app: plana-task1
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plana-task1
spec:
  selector:
    matchLabels:
      app: plana-task1
  replicas: 1
  template:
    metadata:
      labels:
        app: plana-task1
    spec:
      containers:
      - name: plana-task1
        image: meisamhm/plana-task1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
